### ISSUE TITLE
ERROR: attempt to index a nil value

### ISSUE THREAD

**Issue by ulisses-cruz** [nvim-telescope/telescope-ui-select.nvim#28]
From commit   [`78cda7ed94663416f401ca114bde124f178cec05`](https://github.com/nvim-telescope/telescope-ui-select.nvim/commit/78cda7ed94663416f401ca114bde124f178cec05)

Every time I try to open code actions I get the following error:

```bash
Error executing vim.schedule lua callback: ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:34: attempt to index a nil value
stack traceback:
        ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:34: in function <...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:22>
        ...e-ui-select.nvim/lua/telescope/_extensions/ui-select.lua:90: in function 'select'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:720: in function 'on_code_action_results'
        /usr/local/share/nvim/runtime/lua/vim/lsp/buf.lua:789: in function 'handler'
        /usr/local/share/nvim/runtime/lua/vim/lsp.lua:1516: in function ''
        vim/_editor.lua: in function <vim/_editor.lua:0>

```

**Comment by Conni2461** [comment]
fix is here: https://github.com/nvim-telescope/telescope-ui-select.nvim/pull/27

reason is a recent breaking change in neovim nightly, so you can checkout the PR and it should work again, but i cant merge that commit yet because it breaks this plugin for everyone who uses a neovim stable release

**Comment by Conni2461** [comment]
issue was resolved with following commit which just hit master: https://github.com/nvim-telescope/telescope-ui-select.nvim/commit/0fc69ebbf178631b8ab76745459fade062156ec5

**Comment by jhogendorn** [comment]
I'm on the latest commit referenced above, nvim 0.9.4, and i'm running into this issue still. any tips on where i should be debugging?

**Comment by Conni2461** [comment]
This issue should only affect the latest nightly (0.10-dev) we only enabled the fix for versions greater equal 0.10.

0.9 never needed a fix.

Can you maybe provide a error message and the output of `nvim --version`
